### ISSUE TITLE
messing up accountsfile.csv

### ISSUE THREAD

**Issue by dajoker17** [ultrafunkamsterdam/PokeLevel#4]
getaccount replaces all the accounts found by matching the username.  in my case the usernames were xyz1, ... xyz10, xyz11 etc  the usernames were all modified to xyz1, xyz1 xyz1.

changed line 169  in functions.sh to include the trailing comma to fix it up the matching 

GetAccount(){
	#[[ -z $@ ]] && Logger "error" " GetAccount() : No accountname given" && return 1
	sed -i '/'"$b"',''/c\'"$a"','"$b"','"$c"',N' ${ACCOUNTS_FILE}
	[[ $? -eq 0 ]] && return 0 || return 1
}

**Comment by ultrafunkamsterdam** [comment]
Hi @dajoker17. Thank you for contributing. Will test/implement this asap!
I also use accounts starting with the same 3 characters, followed by 3 digits and do not have this issue.
There was a previous bug with account names beginning starting N or Y for example (so obvious, but didn't notice as i don't have them :)), but that's fixed already. Will credit you shortly.
